-- Run after db/migrations/001_initial_schema.sql.
-- Date and bounded dynamic-array functions support both choice and formula questions.

INSERT INTO function_catalog (
  function_name,
  category,
  supports_choice,
  supports_formula,
  difficulty,
  description_ja,
  description_zh,
  blueprint_requirements
) VALUES
  ('SUM',        'aggregate',   TRUE, TRUE,  1, '数値の合計を求めます。',                         '计算数值总和。',                   '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('AVERAGE',    'aggregate',   TRUE, TRUE,  1, '数値の平均を求めます。',                         '计算数值平均值。',                 '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('MAX',        'aggregate',   TRUE, TRUE,  1, '最大の数値を求めます。',                         '返回最大值。',                     '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('MIN',        'aggregate',   TRUE, TRUE,  1, '最小の数値を求めます。',                         '返回最小值。',                     '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('COUNT',      'aggregate',   TRUE, TRUE,  1, '数値が入ったセルの数を数えます。',               '统计包含数值的单元格数量。',       '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('COUNTA',     'aggregate',   TRUE, TRUE,  1, '空白でないセルの数を数えます。',                 '统计非空单元格数量。',             '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('IF',         'logic',       TRUE, TRUE,  2, '条件によって結果を分けます。',                   '根据条件返回不同结果。',           '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('IFS',        'logic',       TRUE, TRUE,  3, '複数の条件を順番に判定します。',                 '依次判断多个条件。',               '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('AND',        'logic',       TRUE, TRUE,  2, 'すべての条件が正しいかを判定します。',           '判断是否所有条件都成立。',         '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('OR',         'logic',       TRUE, TRUE,  2, 'いずれかの条件が正しいかを判定します。',         '判断是否至少一个条件成立。',       '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('IFERROR',    'logic',       TRUE, TRUE,  3, 'エラーの場合に別の結果を返します。',             '在错误时返回替代结果。',           '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('COUNTIF',    'conditional', TRUE, TRUE,  2, '条件に合うセルの数を数えます。',                 '统计符合条件的单元格数量。',       '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('COUNTIFS',   'conditional', TRUE, TRUE,  3, '複数の条件に合うセルの数を数えます。',           '统计符合多个条件的单元格数量。',   '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('SUMIF',      'conditional', TRUE, TRUE,  2, '条件に合う数値を合計します。',                   '对符合条件的数值求和。',           '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('SUMIFS',     'conditional', TRUE, TRUE,  3, '複数の条件に合う数値を合計します。',             '对符合多个条件的数值求和。',       '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('AVERAGEIF',  'conditional', TRUE, TRUE,  2, '条件に合う数値の平均を求めます。',               '计算符合条件数值的平均值。',       '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('MAXIFS',     'conditional', TRUE, TRUE,  3, '複数の条件に合う最大値を求めます。',             '返回符合多个条件的最大值。',       '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('MINIFS',     'conditional', TRUE, TRUE,  3, '複数の条件に合う最小値を求めます。',             '返回符合多个条件的最小值。',       '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('XLOOKUP',    'lookup',      TRUE, TRUE,  3, '対応する値を検索して返します。',                 '查找并返回对应值。',               '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('LEFT',       'text',        TRUE, TRUE,  1, '文字列の左側から文字を取り出します。',           '从文本左侧提取字符。',             '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('RIGHT',      'text',        TRUE, TRUE,  1, '文字列の右側から文字を取り出します。',           '从文本右侧提取字符。',             '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('MID',        'text',        TRUE, TRUE,  2, '文字列の途中から文字を取り出します。',           '从文本中间位置提取字符。',         '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('LEN',        'text',        TRUE, TRUE,  1, '文字列の長さを数えます。',                       '计算文本长度。',                   '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('UPPER',      'text',        TRUE, TRUE,  1, '英字を大文字に変換します。',                     '将英文转换为大写。',               '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('LOWER',      'text',        TRUE, TRUE,  1, '英字を小文字に変換します。',                     '将英文转换为小写。',               '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('PROPER',     'text',        TRUE, TRUE,  2, '各単語の先頭を大文字に変換します。',             '将每个英文单词首字母转换为大写。', '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('SUBSTITUTE', 'text',        TRUE, TRUE,  2, '文字列内の文字を置き換えます。',                 '替换文本中的字符。',               '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('VALUE',      'text',        TRUE, TRUE,  1, '数値を表す文字列を計算可能な数値へ変換します。', '将表示数字的文本转换为可计算的数值。', '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('TEXT',       'text',        TRUE, TRUE,  2, '数値を指定した表示形式の文字列へ変換します。',   '按指定格式将数值转换为文本。',         '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('ABS',        'calculation', TRUE, TRUE,  1, '数値の絶対値を求めます。',                       '计算数值的绝对值。',               '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('ROUND',      'calculation', TRUE, TRUE,  2, '数値を指定した桁数で四捨五入します。',           '按指定小数位四舍五入。',           '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('ROUNDUP',    'calculation', TRUE, TRUE,  2, '数値を指定した桁数で切り上げます。',             '按指定小数位向上取整。',           '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('ROUNDDOWN',  'calculation', TRUE, TRUE,  2, '数値を指定した桁数で切り捨てます。',             '按指定小数位向下取整。',           '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('CEILING',    'calculation', TRUE, TRUE,  2, '数値を指定した倍数に切り上げます。',             '向上舍入到指定倍数。',             '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('SUMPRODUCT', 'calculation', TRUE, TRUE,  4, '対応する数値を掛けて合計します。',               '将对应数值相乘后求和。',           '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('MOD',        'calculation', TRUE, TRUE,  1, '割り算の余りを求めます。',                       '计算除法的余数。',                 '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('YEAR',       'date',        TRUE, TRUE,  1, '日付から年を取り出します。',                     '从日期中提取年份。',               '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('MONTH',      'date',        TRUE, TRUE,  1, '日付から月を取り出します。',                     '从日期中提取月份。',               '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('DAY',        'date',        TRUE, TRUE,  1, '日付から日を取り出します。',                     '从日期中提取日期。',               '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('FILTER',     'dynamic',     TRUE, TRUE,  3, '条件に合う行を動的配列として抽出します。',       '将符合条件的行提取为动态数组。',   '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('SORT',       'dynamic',     TRUE, TRUE,  2, '配列を指定した順序で並べ替えます。',             '按指定顺序对数组排序。',           '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb),
  ('UNIQUE',     'dynamic',     TRUE, TRUE,  2, '配列から重複しない値を返します。',               '返回数组中的唯一值。',             '{"minimum_choice_blueprints":3,"minimum_formula_blueprints":3}'::jsonb)
ON CONFLICT (function_name) DO UPDATE SET
  category = EXCLUDED.category,
  supports_choice = EXCLUDED.supports_choice,
  supports_formula = EXCLUDED.supports_formula,
  difficulty = EXCLUDED.difficulty,
  description_ja = EXCLUDED.description_ja,
  description_zh = EXCLUDED.description_zh,
  blueprint_requirements = EXCLUDED.blueprint_requirements,
  updated_at = CURRENT_TIMESTAMP;
