import type { AdminLocale } from "../../shared/i18n/AdminLocaleProvider.tsx";
import type { ManualQuestionType } from "../../../types/models/manual-question.ts";

const questionTypes: Record<AdminLocale, Record<ManualQuestionType, string>> = {
  ja: { single_choice: "単一選択", multiple_choice: "複数選択", fill_blank: "穴埋め", short_answer: "記述式" },
  zh: { single_choice: "单选题", multiple_choice: "多选题", fill_blank: "填空题", short_answer: "简答题" },
  en: { single_choice: "Single choice", multiple_choice: "Multiple choice", fill_blank: "Fill in the blank", short_answer: "Short answer" },
};

export const authoringCopy = {
  ja: {
    title: "出題管理",
    noSubject: "出題できる担当科目がありません",
    noSubjectDescription: "科目管理者に出題権限の割り当てを依頼してください。",
    loadError: "出題情報を読み込めません",
    loadErrorDescription: "ネットワークまたは科目権限を確認して、もう一度お試しください。",
    retry: "再読み込み",
    configuration: "基本設定",
    authoringCapability: "今回の出題方式",
    authoringCapabilityHint: "この科目に管理者が割り当てた出題機能から選択します。切り替えると未保存の入力内容はリセットされます。",
    excelCapability: "Excel 数式",
    manualCapability: "教員作成問題",
    configurationName: "設定名・試験名",
    configurationPlaceholder: "例：第3回 確認試験",
    duration: "試験時間（分）",
    durationHint: "1～240分。初期値は90分です。",
    roster: "出席ファイル",
    rosterHint: "出席ファイルをアップロードしてください。学籍番号と氏名を自動で読み取ります。",
    rosterChoose: "出席ファイルをアップロード",
    rosterImporting: "読み込み中…",
    rosterReplace: "再アップロード",
    rosterStudentNumber: "学籍番号",
    rosterName: "氏名",
    rosterMore: (count: number) => `ほか ${count}名`,
    rosterStudents: (count: number) => `${count}名`,
    rosterFiles: (count: number) => `${count}ファイル`,
    rosterDuplicates: (count: number) => `重複 ${count}件を統合`,
    mode: "出題モード",
    exam: "正式試験",
    assignment: "課題",
    examDescription: "個別問題、入場承認、時間制限と不正防止を使用します。",
    assignmentDescription: "共通問題、時間制限なし、最大2回提出できます。",
    difficulty: "難易度",
    difficultyLabels: { easy: "易しい", normal: "標準", hard: "難しい", hell: "最難関" },
    questionsPerFunction: "1関数あたりの問題数",
    functions: "対象関数",
    selectedFunctions: (count: number) => `${count}個選択`,
    selectAll: "すべて選択",
    clearAll: "選択解除",
    manualQuestions: "教員作成問題",
    paperStrategy: "出題方法",
    allQuestions: "全問を出題",
    allQuestionsDescription: "登録順のまま、題庫の全問題を全員に出題します。",
    randomSubset: "題庫からランダム出題",
    randomSubsetDescription: "学生ごとに問題を抽出して順番を変え、準備完了後は同じ試験用紙を維持します。",
    publishedQuestionCount: "1人あたりの出題数",
    questionBankSummary: (bankSize: number, paperSize: number) => `題庫 ${bankSize}問 / 出題 ${paperSize}問`,
    paperCountExceedsBank: "出題数は題庫の問題数以下にしてください。",
    addQuestion: "＋ 問題を追加",
    emptyQuestions: "問題はまだありません。形式を選んで追加してください。",
    prompt: "問題文",
    options: "選択肢",
    addOption: "選択肢を追加",
    presetAnswer: "正答",
    clearAnswer: "正答設定を解除",
    fillPassage: "穴埋め本文",
    fillHint: "本文中の語句を選択して空欄に変換します。",
    markBlank: "選択部分を空欄にする",
    acceptedAnswers: "照合する正答（1行に1つ）",
    enableAnswer: "正答を設定",
    referenceAnswer: "校対用の参考答案（任意）",
    image: "問題画像（PNG / JPEG / WebP、1.5MB以下）",
    imageAlt: "画像の説明",
    removeImage: "画像を削除",
    moveUp: "上へ",
    moveDown: "下へ",
    remove: "削除",
    preview: "プレビュー",
    previewWorking: "確認中…",
    previewTitle: "出題プレビュー",
    previewEmpty: "内容を設定してプレビューしてください。",
    previewStale: "内容が変更されています。もう一度プレビューしてください。",
    previewReady: "確認済み",
    save: "履歴に保存",
    saving: "保存中…",
    saved: "設定を保存しました。",
    publish: "試験準備を作成",
    publishing: "作成中…",
    history: "保存済み設定",
    historyEmpty: "保存済み設定はありません。",
    historyRefresh: "更新",
    historyRefreshing: "更新中…",
    historyLoadError: "保存済み設定を読み込めません。",
    copySuffix: "（コピー）",
    loadingConfiguration: "読込中…",
    preparationTitle: "試験を準備しています",
    preparationSummary: (students: number, questions: number) => `${students}名・${questions}問を生成して検証します。`,
    preparationFailed: "試験準備に失敗しました。内容を確認して再実行してください。",
    preparationReady: "試験準備が完了しました。",
    openRoom: "考場管理を開く",
    close: "閉じる",
    questionType: (type: ManualQuestionType) => questionTypes.ja[type],
  },
  zh: {
    title: "出题管理",
    noSubject: "没有可出题的担当科目",
    noSubjectDescription: "请联系科目管理员分配出题权限。",
    loadError: "无法加载出题信息",
    loadErrorDescription: "请检查网络或科目权限后重试。",
    retry: "重新加载",
    configuration: "基本设置",
    authoringCapability: "本次出题方式",
    authoringCapabilityHint: "请从管理员为该科目分配的出题能力中选择；切换后，尚未保存的输入内容会被清空。",
    excelCapability: "Excel 公式",
    manualCapability: "教师自定义题目",
    configurationName: "设置名 / 考试名",
    configurationPlaceholder: "例如：第3次阶段考试",
    duration: "考试时长（分钟）",
    durationHint: "可设置 1–240 分钟，默认 90 分钟。",
    roster: "出席文件",
    rosterHint: "请上传出席文件，会自动读取学号和姓名。",
    rosterChoose: "上传出席文件",
    rosterImporting: "正在读取…",
    rosterReplace: "重新上传",
    rosterStudentNumber: "学号",
    rosterName: "姓名",
    rosterMore: (count: number) => `另有 ${count} 人`,
    rosterStudents: (count: number) => `${count} 人`,
    rosterFiles: (count: number) => `${count} 个文件`,
    rosterDuplicates: (count: number) => `已合并 ${count} 条重复记录`,
    mode: "出题模式",
    exam: "正式考试",
    assignment: "课堂课题",
    examDescription: "使用个别试卷、入场确认、限时与防作弊规则。",
    assignmentDescription: "使用共用试卷，不限时，学生最多提交两次。",
    difficulty: "难度",
    difficultyLabels: { easy: "简单", normal: "标准", hard: "困难", hell: "极难" },
    questionsPerFunction: "每个函数的题量",
    functions: "考试函数",
    selectedFunctions: (count: number) => `已选 ${count} 个`,
    selectAll: "全选",
    clearAll: "清空选择",
    manualQuestions: "教师自定义题目",
    paperStrategy: "组卷方式",
    allQuestions: "全部题目",
    allQuestionsDescription: "按照当前顺序，将题库中的全部题目发给所有学生。",
    randomSubset: "从题库随机抽题",
    randomSubsetDescription: "按学生稳定抽取并随机排序；试卷准备完成后，刷新和重新进入不会换题。",
    publishedQuestionCount: "每份试卷题量",
    questionBankSummary: (bankSize: number, paperSize: number) => `题库 ${bankSize} 题 / 每份试卷 ${paperSize} 题`,
    paperCountExceedsBank: "试卷题量不能超过题库题量。",
    addQuestion: "＋ 添加题目",
    emptyQuestions: "还没有题目，请先选择题型。",
    prompt: "题目内容",
    options: "选项",
    addOption: "添加选项",
    presetAnswer: "正确答案",
    clearAnswer: "清除答案设置",
    fillPassage: "填空正文",
    fillHint: "在正文中选中文字，再将其转换为填空。",
    markBlank: "将选中文字设为空格",
    acceptedAnswers: "校对答案（每行一个）",
    enableAnswer: "预设答案",
    referenceAnswer: "收卷校对用参考答案（可选）",
    image: "题目图片（PNG / JPEG / WebP，最大1.5MB）",
    imageAlt: "图片说明",
    removeImage: "删除图片",
    moveUp: "上移",
    moveDown: "下移",
    remove: "删除",
    preview: "预览",
    previewWorking: "正在校验…",
    previewTitle: "出题预览",
    previewEmpty: "设置内容后进行预览。",
    previewStale: "内容已修改，请重新预览。",
    previewReady: "校验通过",
    save: "保存到历史",
    saving: "正在保存…",
    saved: "设置已保存。",
    publish: "创建考试准备任务",
    publishing: "正在创建…",
    history: "已保存设置",
    historyEmpty: "还没有保存过设置。",
    historyRefresh: "刷新",
    historyRefreshing: "刷新中…",
    historyLoadError: "无法加载已保存设置。",
    copySuffix: "（副本）",
    loadingConfiguration: "正在载入…",
    preparationTitle: "正在准备试卷",
    preparationSummary: (students: number, questions: number) => `正在生成并校验 ${students} 人、共 ${questions} 道题。`,
    preparationFailed: "试卷准备失败，请检查内容后重新执行。",
    preparationReady: "试卷准备完成。",
    openRoom: "进入考场管理",
    close: "关闭",
    questionType: (type: ManualQuestionType) => questionTypes.zh[type],
  },
  en: {
    title: "Authoring", noSubject: "No subject is available for authoring", noSubjectDescription: "Ask a subject administrator to grant authoring permission.",
    loadError: "Authoring information could not be loaded", loadErrorDescription: "Check the connection or your subject permissions and try again.", retry: "Reload",
    configuration: "Basic settings", authoringCapability: "Authoring method for this assessment", authoringCapabilityHint: "Choose from the capabilities assigned to this subject. Switching clears unsaved input.", excelCapability: "Excel formulas", manualCapability: "Teacher-authored questions", configurationName: "Configuration and exam name", configurationPlaceholder: "Example: Unit 3 assessment", duration: "Exam duration (minutes)", durationHint: "Choose 1–240 minutes. The default is 90 minutes.",
    roster: "Attendance file", rosterHint: "Upload the attendance file. Student numbers and names are read automatically.",
    rosterChoose: "Upload attendance file", rosterImporting: "Reading…", rosterReplace: "Upload again", rosterStudentNumber: "Student number", rosterName: "Name", rosterMore: (count: number) => `${count} more students`, rosterStudents: (count: number) => `${count} students`, rosterFiles: (count: number) => `${count} files`, rosterDuplicates: (count: number) => `${count} duplicate records merged`,
    mode: "Delivery mode", exam: "Exam", assignment: "Assignment", examDescription: "Individual papers with admission approval, a time limit, and integrity controls.", assignmentDescription: "A shared paper without a time limit; students may submit up to two attempts.",
    difficulty: "Difficulty", difficultyLabels: { easy: "Easy", normal: "Standard", hard: "Hard", hell: "Expert" }, questionsPerFunction: "Questions per function",
    functions: "Functions", selectedFunctions: (count: number) => `${count} selected`, selectAll: "Select all", clearAll: "Clear selection",
    manualQuestions: "Teacher-authored questions", paperStrategy: "Paper composition", allQuestions: "Use every question", allQuestionsDescription: "Give every student all bank questions in their current order.",
    randomSubset: "Draw randomly from the bank", randomSubsetDescription: "Draw and order questions consistently for each student. Papers remain unchanged after preparation.",
    publishedQuestionCount: "Questions per paper", questionBankSummary: (bankSize: number, paperSize: number) => `${bankSize} in bank / ${paperSize} per paper`, paperCountExceedsBank: "The paper cannot contain more questions than the bank.",
    addQuestion: "+ Add question", emptyQuestions: "No questions yet. Choose a question type to begin.", prompt: "Question", options: "Options", addOption: "Add option", presetAnswer: "Correct answer", clearAnswer: "Remove answer key",
    fillPassage: "Passage", fillHint: "Select text in the passage, then convert it to a blank.", markBlank: "Convert selection to blank", acceptedAnswers: "Accepted answers (one per line)", enableAnswer: "Set answer key", referenceAnswer: "Reference answer for review (optional)",
    image: "Question image (PNG, JPEG, or WebP; up to 1.5 MB)", imageAlt: "Image description", removeImage: "Remove image", moveUp: "Move up", moveDown: "Move down", remove: "Delete",
    preview: "Preview", previewWorking: "Checking…", previewTitle: "Paper preview", previewEmpty: "Complete the settings to preview the paper.", previewStale: "The content has changed. Preview it again.", previewReady: "Validated",
    save: "Save to history", saving: "Saving…", saved: "Configuration saved.", publish: "Prepare exam", publishing: "Creating…", history: "Saved configurations", historyEmpty: "No configurations have been saved.", historyRefresh: "Refresh", historyRefreshing: "Refreshing…", historyLoadError: "Saved configurations could not be loaded.", copySuffix: " (copy)", loadingConfiguration: "Loading…",
    preparationTitle: "Preparing papers", preparationSummary: (students: number, questions: number) => `Generating and validating ${questions} questions for ${students} students.`, preparationFailed: "Paper preparation failed. Review the content and run it again.", preparationReady: "Paper preparation is complete.", openRoom: "Open exam room", close: "Close", questionType: (type: ManualQuestionType) => questionTypes.en[type],
  },
} as const;

export function authoringErrorMessage(error: unknown, locale: AdminLocale): string {
  const fallback = locale === "ja" ? "操作を完了できませんでした。" : locale === "zh" ? "操作未能完成。" : "The operation could not be completed.";
  if (!error || typeof error !== "object") return fallback;
  const record = error as Record<string, unknown>;
  const code = typeof record["code"] === "string" ? record["code"] : null;
  const messages: Record<string, Record<AdminLocale, string>> = {
    NO_FUNCTIONS_SELECTED: { ja: "対象関数を1つ以上選択してください。", zh: "请至少选择一个考试函数。", en: "Select at least one function." },
    INVALID_MANUAL_QUESTION: { ja: "未入力または形式が正しくない問題があります。", zh: "有题目尚未填写完整或格式不正确。", en: "One or more questions are incomplete or invalid." },
    INVALID_MANUAL_PAPER_RULE: { ja: "出題数は1以上、題庫の問題数以下にしてください。", zh: "试卷题量必须是大于0且不超过题库题量的整数。", en: "The paper size must be between one and the number of questions in the bank." },
    NO_MANUAL_QUESTIONS: { ja: "問題を1問以上追加してください。", zh: "请至少添加一道题目。", en: "Add at least one question." },
    INVALID_CONFIGURATION_NAME: { ja: "設定名を1～100文字で入力してください。", zh: "请输入1至100个字符的设置名。", en: "Enter a configuration name between 1 and 100 characters." },
    INVALID_ROSTER: { ja: "学生名簿の内容を確認してください。", zh: "请检查学生名册内容。", en: "Check the student roster." },
    ROSTER_REQUEST_TOO_LARGE: { ja: "名簿を含む送信内容が大きすぎます。", zh: "包含名册的提交内容过大。", en: "The request containing the roster is too large." },
    PREPARATION_NO_PROGRESS: { ja: "試験準備が進行しませんでした。", zh: "试卷准备没有继续推进。", en: "Paper preparation did not make progress." },
    PREPARATION_REQUEST_LIMIT_REACHED: { ja: "想定回数内に試験準備が完了しませんでした。", zh: "试卷准备未在预期批次内完成。", en: "Paper preparation did not finish within the expected number of batches." },
    ROSTER_FILE_REQUIRED: { ja: "出席ファイルをアップロードしてください。", zh: "请上传出席文件。", en: "Upload the attendance file." },
    ROSTER_FILE_EMPTY: { ja: "空の名簿ファイルは使用できません。", zh: "不能使用空的名册文件。", en: "An empty roster file cannot be used." },
    ROSTER_FILE_TOO_LARGE: { ja: "名簿ファイルが上限を超えています。", zh: "名册文件超过大小限制。", en: "The roster file exceeds the size limit." },
    ROSTER_SOURCE_TOTAL_TOO_LARGE: { ja: "選択した名簿ファイルの合計容量が大きすぎます。", zh: "所选名册文件的总大小超出限制。", en: "The selected roster files exceed the combined size limit." },
    ROSTER_FILE_EXTENSION_INVALID: { ja: "CSV、XLS、XLSXの名簿を選択してください。", zh: "请选择 CSV、XLS 或 XLSX 名册。", en: "Select a CSV, XLS, or XLSX roster." },
    ROSTER_NAME_CONFLICT: { ja: "同じ学籍番号に異なる氏名があります。", zh: "同一学号对应了不同姓名。", en: "The same student number is associated with different names." },
    ROSTER_TOO_LARGE: { ja: "このモードの名簿人数上限を超えています。", zh: "名册人数超过当前模式的上限。", en: "The roster exceeds the student limit for this mode." },
    INVALID_ROSTER_ROW: { ja: "学籍番号または氏名が正しくない行があります。", zh: "名册中有学号或姓名格式不正确的行。", en: "One or more rows contain an invalid student number or name." },
    ROSTER_HEADERS_NOT_FOUND: { ja: "学籍番号と氏名の列を確認できません。", zh: "未找到学号和姓名列。", en: "Student number and name columns could not be found." },
  };
  if (code && messages[code]) return messages[code][locale];
  if (record["name"] === "ZodError") {
    return locale === "ja" ? "未入力または形式が正しくない項目があります。" : locale === "zh" ? "有必填项尚未完成或格式不正确。" : "One or more required fields are incomplete or invalid.";
  }
  const message = typeof record["message"] === "string" ? record["message"] : null;
  return message && !/^Request failed\.?$/i.test(message) ? message : fallback;
}
