import type { AdminLocale } from "../../shared/i18n/AdminLocaleProvider.tsx";

export const accountCopy = {
  ja: {
    workspace: "システム管理",
    title: "アカウント管理",
    description: "教員のログイン状態、プラットフォーム権限、担当科目を管理します。",
    create: "アカウントを追加",
    total: (count: number) => `${count}件`,
    identity: "アカウント",
    status: "状態",
    role: "権限",
    memberships: "担当科目",
    actions: "操作",
    active: "有効",
    disabled: "無効",
    migration_pending: "移行待ち",
    super_admin: "スーパー管理者",
    teacher: "教員",
    subject_admin: "科目管理者",
    proctor: "監督者",
    noMemberships: "担当科目なし",
    assign: "科目割当",
    resetPassword: "パスワード",
    disable: "無効化",
    enable: "有効化",
    promote: "管理者へ",
    demote: "教員へ",
    previous: "前へ",
    next: "次へ",
    pagination: "アカウント一覧のページ",
    empty: "アカウントがありません",
    emptyDescription: "最初の教員アカウントを追加してください。",
    loadError: "アカウントを読み込めません",
    loadErrorDescription: "接続状態を確認して再試行してください。",
    retry: "再試行",
    created: "アカウントを作成しました。",
    updated: "アカウント情報を更新しました。",
    refresh: "更新",
    refreshing: "更新中…",
  },
  zh: {
    workspace: "系统管理",
    title: "账户管理",
    description: "管理教师登录状态、平台权限和负责科目。",
    create: "新增账户",
    total: (count: number) => `共 ${count} 个`,
    identity: "账户",
    status: "状态",
    role: "权限",
    memberships: "负责科目",
    actions: "操作",
    active: "启用",
    disabled: "停用",
    migration_pending: "等待迁移",
    super_admin: "超级管理员",
    teacher: "教师",
    subject_admin: "科目管理员",
    proctor: "监考员",
    noMemberships: "尚未分配科目",
    assign: "分配科目",
    resetPassword: "重置密码",
    disable: "停用",
    enable: "启用",
    promote: "设为管理员",
    demote: "设为教师",
    previous: "上一页",
    next: "下一页",
    pagination: "账户列表分页",
    empty: "暂无账户",
    emptyDescription: "请先创建第一个教师账户。",
    loadError: "无法加载账户",
    loadErrorDescription: "请检查连接状态后重试。",
    retry: "重试",
    created: "账户已创建。",
    updated: "账户信息已更新。",
    refresh: "刷新",
    refreshing: "刷新中…",
  },
  en: {
    workspace: "System administration",
    title: "Account management",
    description: "Manage teacher access, platform roles, and assigned subjects.",
    create: "Add account",
    total: (count: number) => `${count} accounts`,
    identity: "Account",
    status: "Status",
    role: "Role",
    memberships: "Assigned subjects",
    actions: "Actions",
    active: "Active",
    disabled: "Disabled",
    migration_pending: "Migration pending",
    super_admin: "Super administrator",
    teacher: "Teacher",
    subject_admin: "Subject administrator",
    proctor: "Proctor",
    noMemberships: "No subjects assigned",
    assign: "Assign subjects",
    resetPassword: "Reset password",
    disable: "Disable",
    enable: "Enable",
    promote: "Make administrator",
    demote: "Make teacher",
    previous: "Previous",
    next: "Next",
    pagination: "Account directory pages",
    empty: "No accounts",
    emptyDescription: "Create the first teacher account to get started.",
    loadError: "Accounts could not be loaded",
    loadErrorDescription: "Check the connection and try again.",
    retry: "Try again",
    created: "Account created.",
    updated: "Account updated.",
    refresh: "Refresh",
    refreshing: "Refreshing…",
  },
} as const satisfies Record<AdminLocale, object>;
