export const subjectCopy = {
  ja: {
    workspace: "システム管理",
    title: "科目管理",
    description: "科目の登録、表示言語、利用状態を管理します。試験作成は各科目の教員が担当します。",
    create: "科目を追加",
    refresh: "更新",
    refreshing: "更新中…",
    directory: "登録科目",
    total: (count: number) => `${count} 科目`,
    empty: "科目がありません",
    emptyDescription: "最初の科目を登録すると、ここに表示されます。",
    loadError: "科目一覧を読み込めません",
    loadErrorDescription: "通信状態を確認して、もう一度お試しください。",
    retry: "再試行",
    created: "科目を登録しました。",
    updated: "科目設定を保存しました。",
    archived: "科目を保管しました。",
    restored: "科目を有効に戻しました。",
    table: "科目管理一覧",
    subject: "科目",
    status: "状態",
    adapter: "出題機能",
    language: "学生画面",
    staff: "担当者",
    actions: "操作",
    active: "有効",
    archivedStatus: "保管中",
    excel: "Excel 数式",
    manual: "教員作成問題",
    legacy: "現行の日英表示",
    japanese: "日本語",
    chinese: "簡体字中国語",
    english: "英語",
    edit: "設定",
    archive: "保管",
    restore: "有効化",
    protected: "標準科目",
  },
  zh: {
    workspace: "系统管理",
    title: "科目管理",
    description: "管理科目登记、显示语言和启用状态；试卷与考场仍由各科目教师负责。",
    create: "新增科目",
    refresh: "刷新",
    refreshing: "刷新中…",
    directory: "已登记科目",
    total: (count: number) => `共 ${count} 门`,
    empty: "暂无科目",
    emptyDescription: "登记第一个科目后将在这里显示。",
    loadError: "无法加载科目列表",
    loadErrorDescription: "请检查网络状态后重试。",
    retry: "重试",
    created: "科目已创建。",
    updated: "科目设置已保存。",
    archived: "科目已归档。",
    restored: "科目已重新启用。",
    table: "科目管理列表",
    subject: "科目",
    status: "状态",
    adapter: "出题能力",
    language: "学生端",
    staff: "负责教师",
    actions: "操作",
    active: "启用",
    archivedStatus: "已归档",
    excel: "Excel 公式",
    manual: "教师自定义题目",
    legacy: "现有日英双语",
    japanese: "日语",
    chinese: "简体中文",
    english: "英语",
    edit: "设置",
    archive: "归档",
    restore: "恢复",
    protected: "系统科目",
  },
  en: {
    workspace: "System administration",
    title: "Subject management",
    description: "Manage subject registration, display languages, and availability. Teachers remain responsible for authoring and exam rooms.",
    create: "Add subject",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    directory: "Registered subjects",
    total: (count: number) => `${count} subjects`,
    empty: "No subjects",
    emptyDescription: "Add the first subject to begin managing the catalogue.",
    loadError: "Subjects could not be loaded",
    loadErrorDescription: "Check the connection and try again.",
    retry: "Try again",
    created: "Subject created.",
    updated: "Subject settings saved.",
    archived: "Subject archived.",
    restored: "Subject restored.",
    table: "Subject management directory",
    subject: "Subject",
    status: "Status",
    adapter: "Authoring capabilities",
    language: "Student interface",
    staff: "Assigned staff",
    actions: "Actions",
    active: "Active",
    archivedStatus: "Archived",
    excel: "Excel formulas",
    manual: "Teacher-authored questions",
    legacy: "Current Japanese and English",
    japanese: "Japanese",
    chinese: "Simplified Chinese",
    english: "English",
    edit: "Settings",
    archive: "Archive",
    restore: "Restore",
    protected: "Core subject",
  },
} as const;
