import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export const STYLE_BUNDLES = [
  {
    output: "public/exam/exam.css",
    sources: [
      "src/client/exam/styles/foundation.css",
      "src/client/exam/styles/entry.css",
      "src/client/exam/styles/workspace.css",
      "src/client/exam/styles/manualResponse.css",
      "src/client/exam/styles/submission.css",
      "src/client/exam/styles/integrity.css",
      "src/client/exam/styles/responsive.css",
    ],
  },
] as const;

export async function renderStyleBundle(sources: readonly string[]): Promise<string> {
  const sections = await Promise.all(sources.map(async (source) => {
    const css = (await readFile(path.join(repositoryRoot, source), "utf8")).trim();
    return `/* Source: ${source} */\n${css}`;
  }));
  return `/* Generated by scripts/build-styles.ts. Do not edit public CSS directly. */\n\n${sections.join("\n\n")}\n`;
}

export async function buildStyles(): Promise<void> {
  for (const bundle of STYLE_BUNDLES) {
    const outputPath = path.join(repositoryRoot, bundle.output);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, await renderStyleBundle(bundle.sources), "utf8");
  }
}

const entryPath = process.argv[1] ? path.resolve(process.argv[1]) : "";
if (entryPath === fileURLToPath(import.meta.url)) await buildStyles();
